package behaviorTree.test
// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Export file: exported/SubBT.groovy
// ---------------------------------------------------------------------

import com.t13max.ai.behavior4j.BTNode
import com.t13max.nms.ai.agent.MonsterAgent

class SubBTDfn {
	Map<Integer, BTNode<MonsterAgent>> data = new HashMap<>();

	{
		
	}

	BTNode<MonsterAgent> getNode(int id) {
		return data.get(id)
	}

}
