name: MelonIsland
version: '${project.version}'
main: com.t13max.plugin.MelonIsland
api-version: '1.20'
author: t13max
description: "foolish melon island"
website: https://gitee.com/t13max/t13max-foolish-melon
loader: com.t13max.plugin.loader.MelonPluginLoader

settings:
  timeout-time: 600
